apiVersion: v1
kind: Service
metadata:
  name: sample-service
  labels:
    name: sample-service
    app: sample
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
  selector:
    name: sample-pod
    app: sample
